### ISSUE TITLE
Inviting new users doesn't work

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/mlavalon#148]
### To replicate:
1. Log in as a user who has permissions to manage/invite users.
2. Attempt to invite a user

### Expected Behavior
1. I don't know actually. I assume the invited user gets an email, and the logged in user get's a flash message that says an email has been sent.

### Actual behavior
* "We're sorry, but something went wrong"
* The container apparently cannot send mail (see comment for stack trace)

### Done when
* invitation for new users can be sent without error
* users can sign up with invitation email.

**Comment by afred** [comment]
### Stack trace from Edge instance:
```
I, [2020-08-04T15:21:08.078539 #947]  INFO -- : Sent mail to james_auclair@wgbh.org (2.9ms)
I, [2020-08-04T15:21:08.078867 #947]  INFO -- : method=POST path=/users/invitation format=html controller=Devise::InvitationsController action=create status=500 error='Errno::ECONNREFUSED: Connection refused - connect(2) for "::1" port 25' duration=17.33 view=0.00 db=3.50 time=4330254.28
F, [2020-08-04T15:21:08.080003 #947] FATAL -- :   
F, [2020-08-04T15:21:08.080049 #947] FATAL -- : Errno::ECONNREFUSED (Connection refused - connect(2) for "::1" port 25):
F, [2020-08-04T15:21:08.080074 #947] FATAL -- :   
F, [2020-08-04T15:21:08.080117 #947] FATAL -- : /usr/local/rvm/rubies/ruby-2.5.8/lib/ruby/2.5.0/resolv-replace.rb:25:in `initialize'
/usr/local/rvm/rubies/ruby-2.5.8/lib/ruby/2.5.0/resolv-replace.rb:25:in `initialize'
/usr/local/rvm/rubies/ruby-2.5.8/lib/ruby/2.5.0/net/smtp.rb:539:in `open'
/usr/local/rvm/rubies/ruby-2.5.8/lib/ruby/2.5.0/net/smtp.rb:539:in `tcp_socket'
/usr/local/rvm/rubies/ruby-2.5.8/lib/ruby/2.5.0/net/smtp.rb:549:in `block in do_start'
/usr/local/rvm/rubies/ruby-2.5.8/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
/usr/local/rvm/rubies/ruby-2.5.8/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
/usr/local/rvm/rubies/ruby-2.5.8/lib/ruby/2.5.0/net/smtp.rb:548:in `do_start'
/usr/local/rvm/rubies/ruby-2.5.8/lib/ruby/2.5.0/net/smtp.rb:518:in `start'
vendor/gems/ruby/2.5.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
vendor/gems/ruby/2.5.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
vendor/gems/ruby/2.5.0/gems/mail-2.7.1/lib/mail/message.rb:2159:in `do_delivery'
vendor/gems/ruby/2.5.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `block in deliver'
vendor/gems/ruby/2.5.0/gems/actionmailer-5.2.3/lib/action_mailer/base.rb:560:in `block in deliver_mail'
vendor/gems/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `block in instrument'
vendor/gems/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
vendor/gems/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `instrument'
vendor/gems/ruby/2.5.0/gems/actionmailer-5.2.3/lib/action_mailer/base.rb:558:in `deliver_mail'
vendor/gems/ruby/2.5.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `deliver'
vendor/gems/ruby/2.5.0/gems/actionmailer-5.2.3/lib/action_mailer/message_delivery.rb:114:in `block in deliver_now'
vendor/gems/ruby/2.5.0/gems/actionmailer-5.2.3/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
vendor/gems/ruby/2.5.0/gems/actionmailer-5.2.3/lib/action_mailer/message_delivery.rb:113:in `deliver_now'
vendor/gems/ruby/2.5.0/gems/devise-4.7.1/lib/devise/models/authenticatable.rb:199:in `send_devise_notification'
vendor/gems/ruby/2.5.0/gems/devise_invitable-1.7.5/lib/devise_invitable/models.rb:210:in `deliver_invitation'
vendor/gems/ruby/2.5.0/gems/devise_invitable-1.7.5/lib/devise_invitable/models.rb:163:in `block in invite!'
vendor/gems/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
vendor/gems/ruby/2.5.0/gems/devise_invitable-1.7.5/lib/devise_invitable/models.rb:152:in `invite!'
vendor/gems/ruby/2.5.0/gems/devise_invitable-1.7.5/lib/devise_invitable/models.rb:327:in `_invite'
vendor/gems/ruby/2.5.0/gems/devise_invitable-1.7.5/lib/devise_invitable/models.rb:333:in `invite!'
vendor/gems/ruby/2.5.0/gems/devise_invitable-1.7.5/app/controllers/devise/invitations_controller.rb:79:in `invite_resource'
vendor/gems/ruby/2.5.0/gems/devise_invitable-1.7.5/app/controllers/devise/invitations_controller.rb:19:in `create'
vendor/gems/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
vendor/gems/ruby/2.5.0/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:194:in `process_action'
vendor/gems/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/rendering.rb:30:in `process_action'
vendor/gems/ruby/2.5.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
vendor/gems/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
vendor/gems/ruby/2.5.0/gems/react-rails-2.5.0/lib/react/rails/controller_lifecycle.rb:31:in `use_react_component_helper'
vendor/gems/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
vendor/gems/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:136:in `run_callbacks'
vendor/gems/ruby/2.5.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:41:in `process_action'
vendor/gems/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
vendor/gems/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
vendor/gems/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `block in instrument'
vendor/gems/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
vendor/gems/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `instrument'
vendor/gems/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
vendor/gems/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
vendor/gems/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
vendor/gems/ruby/2.5.0/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:134:in `process'
vendor/gems/ruby/2.5.0/gems/actionview-5.2.3/lib/action_view/rendering.rb:32:in `process'
vendor/gems/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal.rb:191:in `dispatch'
vendor/gems/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal.rb:252:in `dispatch'
vendor/gems/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
vendor/gems/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:34:in `serve'
vendor/gems/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>'
vendor/gems/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/mapper.rb:48:in `serve'
vendor/gems/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:52:in `block in serve'
vendor/gems/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `each'
vendor/gems/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `serve'
vendor/gems/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:840:in `call'
vendor/gems/ruby/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'
vendor/gems/ruby/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'
vendor/gems/ruby/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'
vendor/gems/ruby/2.5.0/gems/rack-2.0.8/lib/rack/tempfile_reaper.rb:15:in `call'
vendor/gems/ruby/2.5.0/gems/rack-2.0.8/lib/rack/etag.rb:25:in `call'
vendor/gems/ruby/2.5.0/gems/rack-2.0.8/lib/rack/conditional_get.rb:38:in `call'
vendor/gems/ruby/2.5.0/gems/rack-2.0.8/lib/rack/head.rb:12:in `call'
vendor/gems/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
vendor/gems/ruby/2.5.0/gems/rack-2.0.8/lib/rack/session/abstract/id.rb:259:in `context'
vendor/gems/ruby/2.5.0/gems/rack-2.0.8/lib/rack/session/abstract/id.rb:253:in `call'
vendor/gems/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/cookies.rb:670:in `call'
vendor/gems/ruby/2.5.0/gems/active-fedora-12.1.1/lib/active_fedora/ldp_cache.rb:26:in `call'
vendor/gems/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
vendor/gems/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
vendor/gems/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
vendor/gems/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
vendor/gems/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
vendor/gems/ruby/2.5.0/gems/lograge-0.11.0/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
vendor/gems/ruby/2.5.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `block in call'
vendor/gems/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
vendor/gems/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:28:in `tagged'
vendor/gems/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `tagged'
vendor/gems/ruby/2.5.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `call'
vendor/gems/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
vendor/gems/ruby/2.5.0/gems/request_store-1.4.1/lib/request_store/middleware.rb:19:in `call'
vendor/gems/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
vendor/gems/ruby/2.5.0/gems/rack-2.0.8/lib/rack/method_override.rb:22:in `call'
vendor/gems/ruby/2.5.0/gems/rack-2.0.8/lib/rack/runtime.rb:22:in `call'
vendor/gems/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
vendor/gems/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
vendor/gems/ruby/2.5.0/gems/rack-2.0.8/lib/rack/sendfile.rb:111:in `call'
vendor/gems/ruby/2.5.0/gems/rack-cors-1.1.0/lib/rack/cors.rb:100:in `call'
vendor/gems/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:524:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by foglabs-zen** [comment]
Is this moot if we're going to use have okta SSO with avalon? I suspect we will still need to invite non-gbh people to use avalon, at least occasionally

**Comment by foglabs-zen** [comment]
@afred @jasoncorum

**Comment by foglabs-zen** [comment]
Per team:

Closing because SSO is required for all Avalon users.
