### ISSUE TITLE
Avalon - some item pages are not opening and giving errors

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mlavalon#250]
# Details 
Some media is not playable in Avalon. When you click on the title in search results you get an error that states "We're sorry, but something went wrong. If you are the application owner check the logs for more information."

Example: https://avalon.wgbh.org/media_objects/2j62s771f    (M0584624)

This video item is missing a thumbnail when viewed in search results, as many others are, but other items without thumbnails allow you to go to the item page and play media.

Submitted by: Peter Higgins
CC in communications: 
Priority: High (within the week)
URL: https://avalon.wgbh.org/media_objects/2j62s771f
Slack message thread:

**Comment by foglabs** [comment]
this looks like an issue with items in this ingest manifest:
export_non-QCd_FoundSet_2023-11-27_35048.csv

fedora appears to have errored when saving items from this manifest, yielding this great error:
```
status=500 error='Ldp::HttpError: STATUS: 500 org.modeshape.jcr.value.binary.BinaryStoreException: Unable to find binary value with key "8802e828b2b9cf74c52c050a8a1632e07708a8f6" within binary store at "/data/fcrepo.binary.directory"
        at org.modeshape.jcr.value.binary.FileSystemBinaryStore.getInputStream(FileSystemBinaryStore.java:319)
        at org.modeshape.jcr.value.binary.StoredBinaryValue.internalStream(StoredBinaryValue.java:70)
        at org.modeshape.jcr.value.binary.AbstractBinary.getStream(AbstractBinary.java:166)
        at org.fcrepo.kernel.modeshape.FedoraBinaryImpl.getContent(FedoraBinaryImpl.java:123)
        at org.fcrepo.http.api.ContentExposingResource.getBinaryContent(ContentExposingResource.java:357)
        at org.fcrepo.http.api.ContentExposingResource.getContent(ContentExposingResource.java:196)
        at org.fcrepo.http.api.FedoraLdp.getResource(FedoraLdp.java:262)
        at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method...' duration=2062.86 view=0.00 db=220.21 time=18498040.41
```

Testing 3-4 records from this 8k item manifest yielded the same problem as the example record. I'll move this manifest back to the inbox, so that it will be reingested, before verifying that the items saved correctly.

**Comment by ekemeyer** [comment]
Closing -  will make new tickets as other issues reveal themselves
